server:
  port: 8083

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:sqlite:${DB_PATH:./bookings.db}
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false   # suppresses the open-in-view warning

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

car:
  service:
    url: ${CAR_SERVICE_URL:http://localhost:8082}