server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:sqlite:${DB_PATH:./users.db}
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false   # suppresses the open-in-view warning

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: 4567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
  expiration: 86400000